// 난이도(1~10) 순서의 작품 목록
import { dog } from './dog.js';
import { cat } from './cat.js';
import { flower } from './flower.js';
import { cup } from './cup.js';
import { bookmark } from './bookmark.js';
import { house } from './house.js';
import { cicada } from './cicada.js';
import { kabuto } from './kabuto.js';
import { hat } from './hat.js';
import { airplane } from './airplane.js';
import { envelope } from './envelope.js';
import { glider } from './glider.js';
import { whale } from './whale.js';
import { heart } from './heart.js';
import { frame } from './frame.js';
import { duck } from './duck.js';
import { tulip } from './tulip.js';
import { heron } from './heron.js';
import { crane } from './crane.js';
import { masu } from './masu.js';
import { roofhouse } from './roofhouse.js';
import { fox } from './fox.js';
import { panda } from './panda.js';
import { rabbit } from './rabbit.js';
import { watermelon } from './watermelon.js';
import { motorboat } from './motorboat.js';
import { fuji } from './fuji.js';
import { chick } from './chick.js';
import { pig } from './pig.js';
import { koala } from './koala.js';
import { car } from './car.js';
import { goldfish } from './goldfish.js';
import { mouse } from './mouse.js';
import { pencil } from './pencil.js';
import { icecream } from './icecream.js';
import { ufo } from './ufo.js';
import { octopus } from './octopus.js';
import { piano } from './piano.js';
import { foxcub } from './foxcub.js';
import { crab } from './crab.js';
import { penguin } from './penguin.js';
import { elephant } from './elephant.js';
import { monkey } from './monkey.js';
import { candle } from './candle.js';
import { yacht } from './yacht.js';
import { owl } from './owl.js';
import { sandwich } from './sandwich.js';
import { lion } from './lion.js';

export const MODELS = [dog, cat, flower, cup, bookmark, house, cicada, kabuto, hat, airplane, glider, envelope, whale, heart, frame, duck, tulip, heron, masu, roofhouse, crane, fox, panda, rabbit, watermelon, motorboat, fuji, chick, pig, koala, car, goldfish, mouse, pencil, icecream, ufo, octopus, piano, foxcub, crab, penguin, elephant, monkey, candle, yacht, owl, sandwich, lion].sort((a, b) => a.level - b.level);

// 개발 중인 작품: 주소에 ?dev 를 붙였을 때만 목록에 나온다 (검사는 함께 한다)
export const DEV = [];
